spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 3
        max-idle: 2
  datasource:
    url: jdbc:mysql://localhost:3306/e-system?allowPublicKeyRetrieval=true&useSSL=false&charset=utf8mb4
    username: jamie
    password: Test1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging.org.akj.redis.level: DEBUG
